version: '3.4'

x-celery_config: &celery_config
  BROKER_URL: redis://redis:6379/0
  RESULT_BACKEND: redis://redis:6379/0

services:
  react:
    build:
      context: ./react
    volumes:
      - ./react/src:/app/src
      - /app/node_modules
    ports:
      - "3000:3000"
      - "35729:35729"
  mongo:
    build:
      context: ./mongo
    environment:
      <<: *celery_config
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: datafactoring
    ports:
      - "27017:27017"
    expose:
      - "27017"
  flask:
    build:
      context: ./flask
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - ./flask/src:/app/src
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - mongo
      - celery
  celery:
    build:
      context: ./celery
    environment:
      *celery_config
    depends_on:
      - redis
  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    