export const FETCH_CHART_REQUEST = "FETCH_CHART_REQUEST";
export const FETCH_CHART_SUCCESS = "FETCH_CHART_SUCCESS";
export const FETCH_CHART_FAILURE = "FETCH_CHART_FAILURE";

export const FETCH_FUNCTIONS_REQUEST = "FETCH_FUNCTIONS_REQUEST";
export const FETCH_FUNCTIONS_SUCCESS = "FETCH_FUNCTIONS_SUCCESS";
export const FETCH_FUNCTIONS_FAILURE = "FETCH_FUNCTIONS_FAILURE";

export const POST_FILE_REQUEST = "POST_FILE_REQUEST";
export const POST_FILE_SUCCESS = "POST_FILE_SUCCESS";
export const POST_FILE_FAILURE = "POST_FILE_FAILURE";

export const POPUP_OPEN = "POPUP_OPEN";
export const POPUP_CLOSE = "POPUP_CLOSE";
