export const FETCH_CHART_REQUEST = "FETCH_CHART_REQUEST";
export const FETCH_CHART_SUCCESS = "FETCH_CHART_SUCCESS";
export const FETCH_CHART_FAILURE = "FETCH_CHART_FAILURE";

export const POST_FILE_REQUEST = "POST_FILE_REQUEST";
export const POST_FILE_SUCCESS = "POST_FILE_SUCCESS";
export const POST_FILE_FAILURE = "POST_FILE_FAILURE";

export const GET_FUNCTIONS_REQUEST = "GET_FUNCTIONS_REQUEST";
export const GET_FUNCTIONS_SUCCESS = "GET_FUNCTIONS_SUCCESS";
export const GET_FUNCTIONS_FAILURE = "GET_FUNCTIONS_FAILURE";
